name: Add App Installers to Release

on:
  push:
    tags:
      - '*'

jobs:
  build-mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.4
    - name: npm install, build, test
      run: |
        npm install
        npm run build --if-present
        npm test
      env:
        CI: true
    - name: npm package
      run: npm run package:mac
    - name: add app to release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/resting-state-task-0.1.0.dmg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.4
    - name: npm install, build, test
      run: |
        npm install
        npm run build --if-present
        npm test
      env:
        CI: true
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install PsiTurk
      run: pip install psiturk
    - name: Create Psiturk Build
      run: |
        cd psiturkit
        ./psiturk-it -p resting-state-psiturk
        tar -czvf resting-state-psiturk-0.1.0.tar.gz ./resting-state-psiturk
    - name: add app to release
      uses: softprops/action-gh-release@v1
      with:
        files: psiturk/resting-state-psiturk-0.1.0.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: npm package
      run: npm run package:linux
    - name: add app to release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/installers/resting-state_0.1.0_x64.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.4
    - name: npm install
      run: npm install
    - name: npm build
      run: npm run build
    - name: npm test
      run: npm test
      env:
        CI: true
    - name: npm package
      run: npm run package:windows
    - name: add app to release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/installers/resting-state-0.1.0-setup.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
